[project]
name = "logistics"
version = "0.0.1-dev"
description = "Warehouse logistics system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "platformdirs>=4.5.1",
    "toml>=0.10.2",
]
